//! The reproducible compilation manifest.
//!
//! Responsibility: record what one `dictc` run consumed and what it produced -- the
//! whitelisted sources with their content digests, the L3b expansion band and its
//! outcome, the per-section sizes -- and render that record as canonical JSON whose
//! bytes are a function of the inputs alone.
//!
//! Boundaries: this layer never reads a raw source's *content* into the record, only
//! its size, line count and digest; it never compiles anything; and it records no
//! wall-clock time, no host name and no path outside the repository, because any of
//! those would make two runs over the same inputs disagree.
//!
//! # Why a manifest rather than a log line
//!
//! `base.dict` is a shipped artifact, and the question a release has to answer is
//! "which inputs produced these bytes". The build log answers it for the run that
//! produced it and is then gone. The manifest travels with the artifact: its digest is
//! stable across machines, so a rebuild that differs is a difference in the sources
//! rather than in the environment. That is also why a `derived` source is measured
//! here even though `data/sources.toml` deliberately pins no hash for it -- the
//! allowlist cannot pin a file the project generates, but the manifest can record what
//! the generator actually produced.
//!
//! # Scale
//!
//! A manifest also says whether the dictionary it describes is the *product*
//! dictionary or a development subset. `ASM-05` sizes the built-in dictionary for
//! 320k to 400k entries; a build below the floor is what makes long inputs fall back
//! to single characters, so it is worth stating in the build log rather than
//! inferring from a byte count.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use ime_dict::format::{FORMAT_VERSION, SectionKind};
use serde::Serialize;
use sha2::{Digest, Sha256};

use super::budget::{Ledger, SectionUsage};

/// Schema version of the manifest document.
pub const MANIFEST_SCHEMA: u32 = 1;

/// Entry count below which the compiled dictionary is a development word list.
///
/// `ASM-05` sizes the built-in dictionary for 320k to 400k entries. A build under the
/// floor holds a subset of the product word list rather than the product word list,
/// which is the state in which long inputs fall back to single characters.
pub const PRODUCT_ENTRY_FLOOR: u64 = 320_000;

/// Entry count past which the built-in dictionary is oversized.
///
/// `ASM-05` caps the built-in dictionary at 400k entries; words past the cap belong in
/// the optional extension dictionary rather than in the shipped container.
pub const PRODUCT_ENTRY_CEILING: u64 = 400_000;

/// What the allowlist states about one raw source, and where the build read it.
///
/// Five values that always travel together, passed as one so a caller cannot
/// transpose them. The path is the file the build actually consumed rather than a
/// name derived from the id, because the compiler's defaults can be overridden on the
/// command line and a manifest that measured a different file than the build read
/// would be worse than no manifest at all.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceIdentity {
    /// Allowlist id; the raw file is `data/raw/<id>.tsv` unless a caller overrode it.
    pub id: String,
    /// `upstream` (a hash-pinned download) or `derived` (generated by this project).
    pub kind: String,
    /// ADR-0000 layer the source feeds: `L1`, `L2`, `L3`, `L4` or `L5`.
    pub layer: String,
    /// SPDX identifier of the source's licence.
    pub spdx: String,
    /// File the build read.
    pub path: PathBuf,
}

/// One raw source the build consumed, as the manifest records it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SourceRecord {
    /// Allowlist id the source was read under.
    pub id: String,
    /// `upstream` or `derived`.
    pub kind: String,
    /// ADR-0000 layer the source feeds.
    pub layer: String,
    /// SPDX identifier of the source's licence.
    pub spdx: String,
    /// Size of the raw file in bytes.
    pub bytes: u64,
    /// Lines the raw file holds, comments and blanks included.
    pub lines: u64,
    /// SHA256 of the raw file, lower-case hexadecimal.
    ///
    /// This is the field that makes the manifest reproducible: it pins the exact bytes
    /// the build consumed, including for a `derived` source, whose allowlist entry
    /// carries no hash on purpose.
    pub sha256: String,
}

impl SourceRecord {
    /// Measures one raw source: its identity from the allowlist, and its size, line
    /// count and digest from the bytes at the path the build read.
    ///
    /// # Errors
    /// Returns an error when the file cannot be read. A source the allowlist registers
    /// but that was never fetched is an error here rather than an omitted row, because
    /// a manifest that silently drops an input is not a record of the build.
    pub fn measure(identity: SourceIdentity) -> Result<Self> {
        let SourceIdentity {
            id,
            kind,
            layer,
            spdx,
            path,
        } = identity;
        let bytes = fs::read(&path).with_context(|| format!("cannot read {}", path.display()))?;
        Ok(Self {
            id,
            kind,
            layer,
            spdx,
            bytes: bytes.len() as u64,
            lines: bytes.iter().filter(|byte| **byte == b'\n').count() as u64,
            sha256: hex(&Sha256::digest(&bytes)),
        })
    }
}

/// The L3b expansion band and what it produced.
///
/// The band is recorded because it is the one build parameter that changes the output
/// size substantially: `ASM-05` names tightening it from the top 50k words to the top
/// 20k as the remedy when the FST section runs past its ceiling, so a manifest that
/// did not say which band was used could not explain a size difference between two
/// releases.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct ExpansionRecord {
    /// Weight floor at or above which a word is expanded.
    pub band_weight: u32,
    /// The frequency rank the build asked the L4 source for.
    pub band_rank: u64,
    /// Ceiling on the number of keys one word may generate.
    pub cap: u32,
    /// Words inside the band.
    pub band_words: u64,
    /// Words that produced more than one key.
    pub expanded_words: u64,
    /// Keys the expansion added on top of the baseline.
    pub added_keys: u64,
}

/// The container the build wrote.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct DictionaryRecord {
    /// Path of the container, relative to the repository root when it is inside it.
    pub path: String,
    /// Size of the container in bytes.
    pub bytes: u64,
    /// SHA256 of the container, lower-case hexadecimal.
    pub sha256: String,
    /// Entries the container holds.
    pub entries: u64,
    /// Distinct FST keys.
    pub keys: u64,
}

/// Whether a compiled dictionary reaches product scale.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Scale {
    /// The entry count is inside the product-scale window.
    Product,
    /// The entry count is under the floor: a development word list.
    Development {
        /// Entries the dictionary is short of the floor.
        shortfall: u64,
    },
    /// The entry count is past the ceiling the container budget allows.
    Oversized {
        /// Entries the dictionary holds past the ceiling.
        excess: u64,
    },
}

/// What only the compiler knows: the sources it read, the band it used, and the key
/// count it produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuildFacts {
    /// Raw sources the build consumed.
    pub sources: Vec<SourceIdentity>,
    /// The L3b expansion band and its outcome.
    pub expansion: ExpansionRecord,
    /// Distinct FST keys in the container.
    pub keys: u64,
}

/// The compilation manifest: what one `dictc` run consumed and what it produced.
///
/// Every field is public because the document *is* its fields; there is no behaviour
/// behind them, and a reader of the JSON needs the same view the writer had.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Manifest {
    /// Schema version of this document.
    pub schema: u32,
    /// Container format version the output is written in.
    pub format_version: u16,
    /// Raw sources the build consumed, ordered by allowlist id.
    pub sources: Vec<SourceRecord>,
    /// The L3b expansion band and its outcome.
    pub expansion: ExpansionRecord,
    /// Per-section sizes, ordered as the container lays them out.
    pub sections: Vec<SectionUsage>,
    /// The container the build wrote.
    pub dictionary: DictionaryRecord,
}

impl Manifest {
    /// Whether the recorded dictionary reaches product scale.
    ///
    /// The window is `ASM-05`'s: the built-in dictionary is sized for 320k to 400k
    /// entries, and a build below the floor is a subset rather than the product word
    /// list.
    pub fn scale(&self) -> Scale {
        let entries = self.dictionary.entries;
        if entries < PRODUCT_ENTRY_FLOOR {
            Scale::Development {
                shortfall: PRODUCT_ENTRY_FLOOR - entries,
            }
        } else if entries > PRODUCT_ENTRY_CEILING {
            Scale::Oversized {
                excess: entries - PRODUCT_ENTRY_CEILING,
            }
        } else {
            Scale::Product
        }
    }

    /// Entries the recorded container holds.
    pub fn entries(&self) -> u64 {
        self.dictionary.entries
    }

    /// Renders the manifest as canonical JSON.
    ///
    /// Canonical here means a function of the inputs alone: the field order is the
    /// declaration order, the sources are sorted by id, the sections are sorted by the
    /// container's layout order, and nothing in the document comes from the clock or
    /// the environment. The text ends in a newline so it is a well-formed text file.
    ///
    /// # Errors
    /// Returns an error when the document cannot be serialised, which a document made
    /// of plain numbers and strings cannot do in practice.
    pub fn render(&self) -> Result<String> {
        let mut text =
            serde_json::to_string_pretty(self).context("rendering the compilation manifest")?;
        text.push('\n');
        Ok(text)
    }

    /// Writes the manifest and returns the SHA256 of the bytes written.
    ///
    /// # Errors
    /// Returns an error when the manifest cannot be rendered, or when the file cannot
    /// be written.
    pub fn write(&self, path: &Path) -> Result<String> {
        let text = self.render()?;
        fs::write(path, &text).with_context(|| format!("cannot write {}", path.display()))?;
        Ok(hex(&Sha256::digest(text.as_bytes())))
    }
}

/// The manifest path that belongs to one container: `<container>.manifest.json`.
///
/// The manifest is not a second artifact a release has to remember to carry: it sits
/// beside the container under a name derived from it, so moving one moves the other.
/// A path with no file name of its own gets the manifest name alone.
pub fn manifest_path(container: &Path) -> PathBuf {
    let mut name = container.file_name().unwrap_or_default().to_os_string();
    name.push(".manifest.json");
    container.with_file_name(name)
}

/// Records one compilation, writes its manifest beside the container, and returns it.
///
/// The container's size and digest are read back from disk rather than taken from the
/// compiler's counters, so the manifest describes what was written rather than what
/// the compiler meant to write.
///
/// # Errors
/// Returns an error when a source the build read or the container cannot be read, when
/// a section is recorded twice, when the manifest cannot be rendered, or when it
/// cannot be written.
pub fn record_build(
    root: &Path,
    container: &Path,
    ledger: &Ledger,
    facts: BuildFacts,
) -> Result<Manifest> {
    let sources = measured_sources(facts.sources)?;
    let entries = ledger
        .usage_of(SectionKind::Entries)
        .and_then(|row| row.entries)
        .unwrap_or(0);
    let manifest = Manifest {
        schema: MANIFEST_SCHEMA,
        format_version: FORMAT_VERSION,
        sources,
        expansion: facts.expansion,
        sections: ordered_sections(ledger),
        dictionary: describe_container(root, container, entries, facts.keys)?,
    };

    let path = manifest_path(container);
    let digest = manifest.write(&path)?;
    println!("dictc: manifest {} sha256 {digest}", path.display());
    match manifest.scale() {
        Scale::Product => {}
        Scale::Development { shortfall } => println!(
            "dictc: warning: {} entries is {shortfall} short of the product-scale floor \
             {PRODUCT_ENTRY_FLOOR}; this is a development word list, and long inputs \
             will fall back to single characters",
            manifest.entries()
        ),
        Scale::Oversized { excess } => println!(
            "dictc: warning: {} entries is {excess} past the built-in dictionary's ceiling \
             {PRODUCT_ENTRY_CEILING}; truncate the lowest-weight words",
            manifest.entries()
        ),
    }
    Ok(manifest)
}

/// Measures every source the build consumed, ordered by allowlist id.
///
/// The order is a function of the sources rather than of the caller's list, which is
/// what makes two builds of the same inputs render the same manifest. A path breaks a
/// tie between two entries that share an id, so the order stays total.
fn measured_sources(mut sources: Vec<SourceIdentity>) -> Result<Vec<SourceRecord>> {
    sources.sort_by(|left, right| {
        left.id
            .cmp(&right.id)
            .then_with(|| left.path.cmp(&right.path))
    });
    let mut records = Vec::with_capacity(sources.len());
    for identity in sources {
        records.push(SourceRecord::measure(identity)?);
    }
    Ok(records)
}

/// The sections the ledger recorded, in the order the container lays them out.
///
/// The container's own order rather than the table's, because a manifest describes
/// the file it belongs to and the two orders differ.
fn ordered_sections(ledger: &Ledger) -> Vec<SectionUsage> {
    let mut rows = ledger.usage().to_vec();
    rows.sort_by_key(|row| row.kind.as_raw());
    rows
}

/// Reads a container back and describes it.
///
/// The recorded path is relative to the repository root whenever the container is
/// inside it: a manifest travels with an artifact, and an absolute path would name one
/// developer's checkout.
fn describe_container(
    root: &Path,
    container: &Path,
    entries: u64,
    keys: u64,
) -> Result<DictionaryRecord> {
    let bytes =
        fs::read(container).with_context(|| format!("cannot read {}", container.display()))?;
    let relative = container.strip_prefix(root).unwrap_or(container);
    Ok(DictionaryRecord {
        path: relative.to_string_lossy().into_owned(),
        bytes: bytes.len() as u64,
        sha256: hex(&Sha256::digest(&bytes)),
        entries,
        keys,
    })
}

/// Renders a digest as lower-case hexadecimal.
///
/// No hexadecimal encoder is in the workspace's dependency set and this module needs
/// exactly one, so it is three lines here rather than a new dependency.
fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[cfg(test)]
mod tests;
