//! Build script for the user-interface addon.
//!
//! Two jobs, both behind the `fcitx5-host` feature:
//!
//! * probe the Fcitx5 development environment with pkg-config and fail with a
//!   readable message when it is absent, rather than letting the link step emit an
//!   opaque undefined-symbol error;
//! * compile the C++ glue in `src/ffi/cpp/` into a static archive the cdylib links
//!   against, with the language standard and symbol visibility the ABI contract needs.
//!
//! The feature gate is what keeps a plain `cargo check --workspace` working on
//! machines without the Fcitx5 development packages — that is what keeps the
//! pure-Rust CI job dependency-free.
//!
//! # Why this duplicates the engine crate's build script
//!
//! `crates/ime-fcitx5/build.rs` does the same three things. Sharing it would mean a
//! common crate that both libraries link, and the two libraries are dlopen'd
//! independently as separate addons: a link-time relationship between them is exactly
//! what the split exists to remove. The C++ side already accepts the same trade — the
//! `#[repr(C)]` struct definitions are repeated in each glue translation unit, with
//! `addon_glue.cpp` recording why there is deliberately no shared header.

use std::path::PathBuf;

/// Fcitx5 libraries the C++ glue links against. Fcitx5Qt is deliberately excluded:
/// this plugin has no Qt dependency.
const REQUIRED_LIBS: [&str; 3] = ["Fcitx5Core", "Fcitx5Utils", "Fcitx5Config"];

/// Translation units of the C ABI glue, relative to `src/ffi/cpp/`.
///
/// `ui_addon_glue.cpp` owns the loadable-library entry points, the handshake state and
/// the addon factory; `ui_glue.cpp` owns the `fcitx::UserInterface` subclass and the
/// two calls into `UserInterfaceManager`. Splitting them mirrors the engine crate's
/// `addon_glue.cpp` / `engine_glue.cpp` pair.
const GLUE_SOURCES: [&str; 2] = ["ui_addon_glue.cpp", "ui_glue.cpp"];

/// The addon factory symbol Fcitx5 resolves with `dlsym` after `dlopen`.
///
/// Both addons export this name. That is not a collision: Fcitx5 `dlopen`s each
/// library separately and resolves the symbol inside that handle, so the two never
/// meet in one symbol namespace.
const FACTORY_SYMBOL: &str = "fcitx_addon_factory_instance";

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    // Declared for every build, feature or not. Without it the `#[cfg(fcitx5_host)]`
    // gates in the crate are reported as unexpected cfg values, and the `-D warnings`
    // gate turns that into a failure of the pure-Rust job.
    println!("cargo::rustc-check-cfg=cfg(fcitx5_host)");

    if std::env::var_os("CARGO_FEATURE_FCITX5_HOST").is_none() {
        return;
    }

    println!("cargo::rerun-if-changed=src/ffi/cpp");

    let mut include_paths: Vec<PathBuf> = Vec::new();
    for lib in REQUIRED_LIBS {
        match pkg_config::probe_library(lib) {
            Ok(library) => include_paths.extend(library.include_paths),
            Err(err) => abort_missing_dev_package(lib, &err),
        }
    }

    compile_glue(&include_paths);
    emit_link_directives();
    keep_factory_symbol();

    // Lets Rust code distinguish "linked against a real Fcitx5" from "mock host only".
    println!("cargo::rustc-cfg=fcitx5_host");
}

/// Compiles the C++ glue into a static archive that the cdylib links against.
///
/// `-std=c++17` matches the standard Fcitx5 5.1 itself is built with; a newer standard
/// risks ABI drift in the classes the glue derives from. `-fvisibility=default` keeps
/// the factory symbol generated by `FCITX_ADDON_FACTORY` exported — it is the default
/// for a build without `-fvisibility=hidden`, and it is stated explicitly because
/// hiding that symbol would produce a library Fcitx5 silently cannot load.
fn compile_glue(include_paths: &[PathBuf]) {
    let mut build = cc::Build::new();
    build
        .cpp(true)
        .std("c++17")
        .flag("-fvisibility=default")
        .flag("-Wall");
    for include in include_paths {
        build.include(include);
    }
    for source in GLUE_SOURCES {
        build.file(format!("src/ffi/cpp/{source}"));
    }
    build.compile("rspinyin_ui_glue");
}

/// Emits the Fcitx5 link directives.
///
/// The pkg-config probe above already emitted them, but it has to run before the glue
/// is compiled, because the glue needs the include directories. That places the
/// directives ahead of the glue archive on the linker command line, and with
/// `--as-needed` — the default on Debian and Ubuntu toolchains — a shared library
/// listed before the objects that need it is dropped, surfacing much later as
/// undefined `fcitx::...` symbols. Repeating the directives after the archive is
/// harmless: a library that is already loaded is simply found again.
fn emit_link_directives() {
    for lib in REQUIRED_LIBS {
        println!("cargo::rustc-link-lib={lib}");
    }
}

/// Forces the archive member that defines the addon factory to be linked in.
///
/// Nothing on the Rust side references the C++ factory: Fcitx5 reaches it by name after
/// `dlopen`. Without an explicit reference the linker is free to drop the archive member
/// as unused, producing a library that loads and contains no addon.
///
/// Exporting it is a separate problem that no linker flag can solve here — see the
/// comment on `fcitx_addon_factory_instance` in `src/ffi/abi.rs`. The symbol is exported
/// from Rust, because rustc's generated version script only lists Rust-exported symbols.
fn keep_factory_symbol() {
    println!("cargo::rustc-link-arg=-Wl,--undefined={FACTORY_SYMBOL}");
}

/// Aborts the build with an actionable message when an Fcitx5 development package is
/// missing.
///
/// A build script has no error channel other than failing, so this aborts rather than
/// returning. The `platform/fcitx5/dev-missing` prefix is part of the diagnostic
/// contract and is asserted by the acceptance tests, so it must not be reworded.
#[allow(clippy::panic)] // Build scripts have no error channel; aborting is the contract.
fn abort_missing_dev_package(lib: &str, err: &pkg_config::Error) -> ! {
    panic!(
        "platform/fcitx5/dev-missing: could not find the Fcitx5 development package \
         `{lib}` via pkg-config ({err}).\n\
         Install it with one of:\n  \
         Debian/Ubuntu: sudo apt install libfcitx5core-dev libfcitx5utils-dev libfcitx5config-dev\n  \
         Fedora:        sudo dnf install fcitx5-devel\n  \
         Arch:          sudo pacman -S fcitx5\n\
         Alternatively, build without the `fcitx5-host` feature to compile only the \
         pure-Rust side."
    )
}
