//! The holdout generator: a held-out evaluation set derived from the corpus.
//!
//! Responsibility: draw the set a tuning run is measured against -- an equal quota of
//! usable corpus words from each of four frequency bands, every row carrying the layer
//! that has to serve it -- and write it out.
//!
//! Boundaries: this layer writes exactly one file, and only once the whole selection has
//! been made -- a corpus too small to fill a band must leave the previous file untouched
//! rather than half-written. It never scores anything: a generated row carries no weight,
//! because the set is drawn from corpus frequency, not from a measured preference.
//!
//! # Why the set is stratified
//!
//! Taking the most frequent corpus words outright answers a question nobody asks. The head
//! of a frequency list is a few thousand words, so a set of that size drawn that way is
//! nearly all single characters, and a ranking difference among the words a user actually
//! types cannot show up in it. The set is therefore cut into the four bands of the corpus
//! ranking -- the top thousand, the next nine thousand, the next forty thousand, and the
//! tail -- and every band contributes the same quota, so the tail weighs as much as the
//! head.
//!
//! The top band is a thousand words wide by construction, so it contributes all of them
//! and the bands below it fill the quota the requested size divides into. The set is
//! therefore at most `--holdout-rows` rows, and the floor of [`MIN_HOLDOUT_ROWS`] is what
//! it has to reach before it is written at all.
//!
//! # What the source column says
//!
//! The third column names the layer that has to serve the word under the key the row
//! states. It is what lets a reader attribute a miss to a mechanism rather than to the
//! set:
//!
//! * `L1` -- every character of the word carries one reading, so the L3a baseline key is
//!   the only key the word has. A miss is a ranking problem in the word list.
//! * `L3b` -- some character carries several readings, so the baseline is a guess the
//!   frequency-targeted expansion has to back up with the word's other keys. The row
//!   states the baseline key, because the project holds no second pronunciation source to
//!   name a different one from.
//! * `L3c` -- the correction table states a reading the baseline does not, and the row
//!   states that corrected key. A miss is a correction the table does not state.
//!
//! # Reproducibility
//!
//! Nothing here samples, times or hashes: the selection is a sort and a truncation, every
//! comparison ends on the text, and the corpus is ranked from its own counts rather than
//! from the order its lines arrive in. The same corpus, the same L1 table and the same
//! correction table produce a byte-identical file, which is what lets one run record a
//! baseline and a later run claim an improvement over it.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, anyhow, ensure};

use crate::dictc::quality::{ReadingSource, key_of, load_corrections};

use super::io::{
    baseline_key, data_lines, fold_reading, has_polyphone, load_l1_readings, load_rows, read_text,
};
use super::{MIN_HOLDOUT_ROWS, TuneArgs};

/// Longest word a generated holdout row may name, in characters.
const MAX_HOLDOUT_CHARS: usize = 6;

/// Header of the file the generator writes.
///
/// The columns are spelled out here rather than only in this module's documentation
/// because the file travels: whoever opens it has the header and nothing else.
const HEADER: &str = "\
# rspinyin holdout evaluation set, generated by `xtask tune --gen-holdout`.
# Regenerate rather than edit. Columns: pinyin <TAB> expected <TAB> source.
#   pinyin    the ASCII keystrokes a user types for the word
#   expected  the word that has to rank first
#   source    the layer that has to serve it under that key: L1, L3b or L3c
# The rows are an equal quota from each of four bands of the corpus ranking, and none
# of them repeats a word or a key the tuning set already covers. The top band holds a
# thousand words, so it contributes all of them. Blank lines and `#` lines are skipped.
";

/// One frequency band of the corpus ranking.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) struct Stratum {
    /// Name the band carries in the build log.
    pub(super) label: &'static str,
    /// First corpus rank the band covers, one-based and inclusive.
    pub(super) first: u32,
    /// Last corpus rank the band covers, one-based and inclusive.
    pub(super) last: u32,
}

impl Stratum {
    /// Whether a one-based corpus rank falls inside the band.
    pub(super) fn contains(self, rank: u32) -> bool {
        rank >= self.first && rank <= self.last
    }
}

/// The four bands a generated holdout set is stratified by.
///
/// They are bands of a *ranking* rather than per-word frequency cut-offs, because the
/// corpus is a word list with counts and not a token stream: every word in it has a rank,
/// while a count is only comparable with the counts of the same corpus.
pub(super) const STRATA: [Stratum; 4] = [
    Stratum {
        label: "top 1k",
        first: 1,
        last: 1_000,
    },
    Stratum {
        label: "1k-10k",
        first: 1_001,
        last: 10_000,
    },
    Stratum {
        label: "10k-50k",
        first: 10_001,
        last: 50_000,
    },
    Stratum {
        label: "50k+",
        first: 50_001,
        last: u32::MAX,
    },
];

/// A band the corpus could not contribute to at all.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(super) struct Shortfall {
    /// Name of the band that contributed nothing.
    pub(super) band: &'static str,
}

impl Shortfall {
    /// Renders the shortfall as the error the generator reports.
    fn render(self, corpus: &Path) -> anyhow::Error {
        anyhow!(
            "{}: the {} band of the corpus holds no usable word; every band has to \
             contribute, or the set measures the part of the frequency list it kept",
            corpus.display(),
            self.band
        )
    }
}

/// One corpus word the generator may keep, with the rank its count earned it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(super) struct Candidate<'a> {
    /// The word itself.
    pub(super) word: &'a str,
    /// One-based position in the corpus ranking by descending count.
    pub(super) rank: u32,
    /// The key the word is looked up under, composed from the first reading of every
    /// character.
    pub(super) key: String,
}

/// Rows the generator refused, by reason.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct Skips {
    /// Lines whose count column is not a number.
    bad_count: u64,
    /// Lines that carry no word, or a word that is not made of Han characters.
    non_han: u64,
    /// Words longer than [`MAX_HOLDOUT_CHARS`] characters.
    too_long: u64,
    /// Words naming a character the L1 table does not cover.
    uncovered: u64,
    /// Words, or keys, the tuning set already covers.
    overlap: u64,
    /// Words the corpus states more than once.
    duplicate: u64,
}

impl Skips {
    /// Rows the counters account for.
    fn total(self) -> u64 {
        self.bad_count
            + self.non_han
            + self.too_long
            + self.uncovered
            + self.overlap
            + self.duplicate
    }

    /// The counters as one log line.
    fn render(self) -> String {
        format!(
            "bad-count {}, non-han {}, too-long {}, uncovered {}, overlap {}, duplicate {}",
            self.bad_count,
            self.non_han,
            self.too_long,
            self.uncovered,
            self.overlap,
            self.duplicate
        )
    }
}

/// One row of the file the generator writes.
#[derive(Clone, Debug, PartialEq, Eq)]
struct HoldoutRow<'a> {
    /// The key the row is measured under.
    key: String,
    /// The word that has to rank first.
    word: &'a str,
    /// The layer that has to serve the word under the key.
    source: ReadingSource,
}

/// Returns `true` for the Han ranges a holdout word may be made of.
pub(super) fn is_han(character: char) -> bool {
    matches!(
        character as u32,
        0x3400..=0x4DBF | 0x4E00..=0x9FFF | 0xF900..=0xFAFF | 0x2_0000..=0x2_FA1F
    )
}

/// Whether `word` is a word the holdout set may carry: a non-empty run of Han characters.
///
/// The emptiness check is not redundant with the range check: every character of an empty
/// string is a Han character, and an empty word would otherwise enter the set under an
/// empty key and be measured against a lookup no user can type.
fn is_holdout_word(word: &str) -> bool {
    !word.is_empty() && word.chars().all(is_han)
}

/// Derives the holdout set from the corpus and writes it out.
///
/// The rows are drawn in equal numbers from the four bands of the corpus ranking, and none
/// of them repeats a word or a key the tuning set already covers, so the two sets never
/// measure the same thing twice.
///
/// # Errors
///
/// Returns an error when a file cannot be read or written, when the correction table
/// cannot be read, when a band of the corpus holds no usable word, or when the corpus
/// cannot supply [`MIN_HOLDOUT_ROWS`] usable rows in total.
pub(super) fn generate_holdout(root: &Path, args: &TuneArgs) -> Result<()> {
    let readings = load_l1_readings(&root.join(&args.l1))?;
    let first = first_readings(&readings);
    let evaluation = load_rows(&root.join(&args.eval))?;
    let excluded_words: BTreeSet<&str> = evaluation.iter().map(|row| row.word.as_str()).collect();
    let excluded_keys: BTreeSet<&str> = evaluation.iter().map(|row| row.key.as_str()).collect();
    let corrections = correction_index(&root.join(&args.polyphone))?;

    let corpus_path = root.join(&args.corpus);
    let text = read_text(&corpus_path)?;
    let mut skips = Skips::default();
    let ranked = rank_corpus(&text, &mut skips);
    let candidates =
        collect_candidates(&ranked, &first, &excluded_words, &excluded_keys, &mut skips);
    let selected = select_stratified(&candidates, args.holdout_rows / STRATA.len())
        .map_err(|short| short.render(&corpus_path))?;
    ensure!(
        selected.len() >= MIN_HOLDOUT_ROWS,
        "{}: the corpus yields {} usable rows across its bands, {MIN_HOLDOUT_ROWS} are \
         required before a rate over the set resolves a difference between two \
         dictionaries; raise --holdout-rows",
        corpus_path.display(),
        selected.len()
    );
    let rows: Vec<HoldoutRow<'_>> = selected
        .into_iter()
        .map(|candidate| holdout_row(candidate, &readings, &corrections))
        .collect();

    let holdout_path = root.join(&args.holdout);
    fs::write(&holdout_path, render_holdout(&rows))
        .with_context(|| format!("cannot write {}", holdout_path.display()))?;
    println!(
        "tune: {} rows written to {} ({} skipped: {})",
        rows.len(),
        holdout_path.display(),
        skips.total(),
        skips.render()
    );
    Ok(())
}

/// The first reading of every character, which is what a baseline key is composed from.
fn first_readings(readings: &BTreeMap<char, Vec<String>>) -> BTreeMap<char, String> {
    let mut first = BTreeMap::new();
    for (character, all) in readings {
        if let Some(reading) = all.first() {
            first.insert(*character, reading.clone());
        }
    }
    first
}

/// Parses the corpus and ranks it by descending count.
///
/// The ranking is computed here rather than taken from the file order: a band has to be a
/// function of the corpus and not of the order its lines happen to be written in, so a
/// corpus that is not sorted at all still yields the same set. Ties break on the text, for
/// the same reason.
fn rank_corpus<'a>(text: &'a str, skips: &mut Skips) -> Vec<(&'a str, u32)> {
    let mut ranked: Vec<(&str, u32)> = Vec::new();
    for (_, line) in data_lines(text) {
        let mut columns = line.split('\t');
        let word = columns.next().unwrap_or_default();
        match columns.next().unwrap_or_default().parse::<u32>() {
            Ok(count) => ranked.push((word, count)),
            Err(_) => skips.bad_count += 1,
        }
    }
    ranked.sort_by(|left, right| right.1.cmp(&left.1).then_with(|| left.0.cmp(right.0)));
    ranked
}

/// Scans the ranked corpus for rows the tuning set does not already cover.
///
/// A candidate keeps the rank it holds in the whole corpus rather than its position among
/// the survivors: a band is a band of the corpus, so dropping an unusable row from the
/// count would shift every later word into an earlier band and make the set depend on what
/// was skipped.
fn collect_candidates<'a>(
    ranked: &[(&'a str, u32)],
    first: &BTreeMap<char, String>,
    excluded_words: &BTreeSet<&str>,
    excluded_keys: &BTreeSet<&str>,
    skips: &mut Skips,
) -> Vec<Candidate<'a>> {
    let mut seen: BTreeSet<&str> = BTreeSet::new();
    let mut candidates = Vec::new();
    for (index, (word, _)) in ranked.iter().enumerate() {
        let rank = u32::try_from(index).unwrap_or(u32::MAX).saturating_add(1);
        if !seen.insert(word) {
            skips.duplicate += 1;
            continue;
        }
        if !is_holdout_word(word) {
            skips.non_han += 1;
            continue;
        }
        if word.chars().count() > MAX_HOLDOUT_CHARS {
            skips.too_long += 1;
            continue;
        }
        let Some(key) = baseline_key(word, first) else {
            skips.uncovered += 1;
            continue;
        };
        if excluded_words.contains(word) || excluded_keys.contains(key.as_str()) {
            skips.overlap += 1;
            continue;
        }
        candidates.push(Candidate { word, rank, key });
    }
    candidates
}

/// Keeps up to `quota` candidates from every frequency band.
///
/// A band contributes its quota or every word it holds, whichever is fewer. The top band
/// of a frequency list is a thousand words wide by construction, so no quota above a
/// thousand can be met from it, and the bands below it are the ones with room to spare.
/// The candidates arrive in corpus rank order, so a band keeps its most frequent words and
/// the result stays in rank order.
///
/// # Errors
///
/// Returns the first band that contributes nothing at all: a set with a band missing
/// measures the part of the frequency list it kept and calls it the language.
pub(super) fn select_stratified<'c, 'a>(
    candidates: &'c [Candidate<'a>],
    quota: usize,
) -> Result<Vec<&'c Candidate<'a>>, Shortfall> {
    let mut kept: Vec<&'c Candidate<'a>> = Vec::new();
    let mut counts = [0usize; STRATA.len()];
    for candidate in candidates {
        let Some(index) = STRATA.iter().position(|band| band.contains(candidate.rank)) else {
            continue;
        };
        if counts[index] >= quota {
            continue;
        }
        counts[index] += 1;
        kept.push(candidate);
    }
    for (band, count) in STRATA.iter().zip(counts) {
        if count == 0 {
            return Err(Shortfall { band: band.label });
        }
    }
    Ok(kept)
}

/// Attributes one selected candidate to a layer and resolves the key it is measured under.
fn holdout_row<'a>(
    candidate: &Candidate<'a>,
    readings: &BTreeMap<char, Vec<String>>,
    corrections: &BTreeMap<String, String>,
) -> HoldoutRow<'a> {
    let polyphone = has_polyphone(candidate.word, readings);
    let (key, source) = attribute(
        candidate.word,
        candidate.key.clone(),
        polyphone,
        corrections,
    );
    HoldoutRow {
        key,
        word: candidate.word,
        source,
    }
}

/// Which layer has to serve a word, and under which key.
///
/// The three answers are decided from the project's own data rather than from a second
/// pronunciation source: the correction table states the readings the project has settled
/// on, and the L1 table says whether a word's reading is forced at all. A row whose
/// reading the table restates is a baseline row, because a confirmation changes nothing.
pub(super) fn attribute(
    word: &str,
    baseline: String,
    polyphone: bool,
    corrections: &BTreeMap<String, String>,
) -> (String, ReadingSource) {
    match corrections.get(word) {
        // The table states a reading the baseline does not: the row is what serves the
        // word, and the corrected key is the one the case is measured under.
        Some(reading) if *reading != baseline => (reading.clone(), ReadingSource::L3c),
        Some(_) => (baseline, ReadingSource::L1),
        // No row states the word, but one of its characters carries several readings, so
        // the baseline is not the only reading the word could have and the expansion is
        // what has to serve it under the others.
        None if polyphone => (baseline, ReadingSource::L3b),
        None => (baseline, ReadingSource::L1),
    }
}

/// Indexes the correction table by word: the key each row's reading spells.
///
/// A row whose reading has no legal segmentation cannot match any key, so it is dropped
/// and counted rather than refused: the compiler already asserts that every row it reads
/// is a legal syllable sequence, and failing here as well would report one defect twice.
///
/// # Errors
///
/// Returns an error when the table cannot be read or when a row of it is malformed.
fn correction_index(path: &Path) -> Result<BTreeMap<String, String>> {
    let mut index = BTreeMap::new();
    let mut unreadable = 0u64;
    for row in load_corrections(path)? {
        match fold_reading(&row.reading).and_then(|folded| key_of(&folded)) {
            Some(key) => {
                index.insert(row.word, key);
            }
            None => unreadable += 1,
        }
    }
    println!(
        "tune: L3c {} corrections from {}, {unreadable} unreadable",
        index.len(),
        path.display()
    );
    Ok(index)
}

/// Renders the holdout document: the header, then one `key<TAB>word<TAB>source` row each.
fn render_holdout(rows: &[HoldoutRow<'_>]) -> String {
    let mut out = String::with_capacity(HEADER.len() + rows.len() * 32);
    out.push_str(HEADER);
    for row in rows {
        out.push_str(&row.key);
        out.push('\t');
        out.push_str(row.word);
        out.push('\t');
        out.push_str(row.source.as_str());
        out.push('\n');
    }
    out
}
